### ISSUE TITLE
Not able to change solver

### ISSUE THREAD

**Issue by Mallikarjun29** [nariaki3551/ppulp#2]
Everything is great until we are not able to change the solver.
`status=prob.solve(GLPK())` 
`TypeError: LpProblem.solve() takes 1 positional argument but 2 were given`

**Comment by n-tateiwa** [comment]
@Mallikarjun29
Thank you for your feedback!
I modified the codes, and you can specify the solver using the latest script.

I checked that the following code works well.

```python
from ppulp import *
from pulp import GLPK


x = LpVariable("x")
y = LpVariable("y")

prob = LpProblem(sense=LpMinimize)
prob += x + y
prob += x + y >= 2

prob.solve(GLPK())
```

**Comment by Mallikarjun29** [comment]
That was quick. Thank you!
